const initialState = {
  currentUser: {},
  word: '',
  date: 0,
  shortdef: '',
  etymology: [[]],
  languages: [],
  currentLocation: [{lat: 0, lng: 0}],
  mostCommonWord: '',
  userMap: {
    user_id: null,
    word_name: '',
    etymology: '',
    coordinates: {}
  },
  allTheLanguages: [ 
    'Abkhazian',
    'Afar',
    'Afrikaans',
    'Akan',
    'Albanian',
    'Algonquian',
    'Algonquian,',
    'Amharic',
    'Arabic',
    'Aragonese',
    'Armenian',
    'Assamese',
    'Avaric',
    'Avestan',
    'Aymara',
    'Azerbaijani',
    'Bambara',
    'Bantu',
    'Bashkir',
    'Basque',
    'Belarusian',
    'Bengali',
    'Bihari',
    'Bislama',
    'Bosnian',
    'Breton',
    'Bulgarian',
    'Burmese',
    'Catalan', 
    'Valencian',
    'Central Khmer',
    'Chamorro',
    'Chechen',
    'Chichewa', 
    'Chewa', 
    'Nyanja',
    'Chinese',
    'Mandarin',
    'Cantonese',
    'Church Slavonic', 
    'Old Bulgarian', 
    'Old Church Slavonic',
    'Slavonic',
    'Chuvash',
    'Cornish',
    'Corsican',
    'Cree',
    'Croatian',
    'Czech',
    'Danish',
    'Divehi', 
    'Dhivehi', 
    'Maldivian',
    'Dutch', 
    'Dutch,',
    'Flemish',
    'Dzongkha',
    'English',
    'English,',
    'Esperanto',
    'Estonian',
    'Egyptian',
    'Ewe',
    'Faroese',
    'Fijian',
    'Finnish',
    "Anglo-French",
    "Anglo-French,",
    'French',
    'French,',
    'Fulah',
    'Gaelic', 
    'Scottish', 
    'Gaelic',
    'Galician',
    'Ganda',
    'Georgian',
    'German',
    'Germanic',
    'Goth',
    'Gothic',
    'German,',
    'Germanic,',
    'Goth,',
    'Gothic,',
    'Gikuyu', 
    'Kikuyu',
    'Greek',
    'Greenlandic', 
    'Kalaallisut',
    'Guarani',
    'Gujarati',
    'Haitian',
    'Hausa',
    'Hebrew',
    'Herero',
    'Hindi',
    'Hiri Motu',
    'Hungarian',
    'Icelandic',
    'Ido',
    'Igbo',
    'Indonesian',
    'Interlingue',
    'Inuktitut',
    'Inupiaq',
    'Irish',
    'Italian',
    'Japanese',
    'Javanese',
    'Kannada',
    'Kanuri',
    'Kashmiri',
    'Kazakh',
    'Kimbundu',
    'Kinyarwanda',
    'Komi',
    'Kongo',
    'Korean',
    'Kwanyama', 
    'Kuanyama',
    'Kurdish',
    'Kyrgyz',
    'Lao',
    'Latin',
    'Latin,',
    'Latvian',
    'Letzeburgesch', 
    'Luxembourgish',
    'Limburgish', 
    'Limburgan', 
    'Limburger',
    'Lingala',
    'Lithuanian',
    'Lithuanian,',
    'Louisiana',
    'Luba-Katanga',
    'Macedonian',
    'Malagasy',
    'Malay',
    'Malayalam',
    'Maltese',
    'Manx',
    'Maori',
    'Marathi',
    'Marshallese',
    'Moldovan', 
    'Moldavian', 
    'Romanian',
    'Mongolian',
    'Nauru',
    'Navajo', 
    'Navajo,', 
    'Navaho',
    'Nahuatl',
    'Nahuatl,',
    'Northern Ndebele',
    'Ndonga',
    'Nepali',
    'Northern Sami',
    'Norwegian',
    'Nordic',
    'Norse',
    'Norwegian Bokmål',
    'Norwegian Nynorsk',
    'Nuosu', 
    'Sichuan Yi',
    'Occitan',
    'Ojibwa',
    'Oriya',
    'Oromo',
    'Ossetian', 
    'Ossetic',
    'Pali',
    'Panjabi', 
    'Punjabi',
    'Pashto', 
    'Pushto',
    'Persian',
    'Polish',
    'Portuguese',
    'Quechua',
    'Romansh',
    'Rundi',
    'Russian,',
    'Russian',
    'Samoan',
    'Sango',
    'Sanskrit',
    'Sardinian',
    'Serbian',
    'Shona',
    'Sindhi',
    'Sinhala', 'Sinhalese',
    'Slovak',
    'Slovenian',
    'Somali',
    'Sotho, Southern',
    'South Ndebele',
    'Spanish', 
    'Spanish,',
    'Castilian',
    'Castilian,',
    'Sundanese',
    'Swahili',
    'Swati',
    'Swedish',
    'Tagalog',
    'Tahitian',
    'Tajik',
    'Tamil',
    'Tatar',
    'Telugu',
    'Thai',
    'Tibetan',
    'Tigrinya',
    'Tonga (Tonga Islands)',
    'Tsonga',
    'Tswana',
    'Turkish',
    'Turkmen',
    'Twi',
    'Uighur', 
    'Uyghur',
    'Ukrainian',
    'Urdu',
    'Uzbek',
    'Venda',
    'Vietnamese',
    'Volap_k',
    'Walloon',
    'Welsh',
    'Western Frisian',
    'Wolof',
    'Xhosa',
    'Yiddish',
    'Yiddish,',
    'Yoruba',
    'Zhuang', 
    'Chuang',
    'Zulu' 
  ],
  languagesToCoordinates: [{
    English: {lat: 54.0000, lng: -2.0000},
    "English,": {lat: 54.0000, lng: -2.0000},
    "Anglo-French": {lat: 46.0000, lng: 2.0000},
    "Anglo-French,": {lat: 46.0000, lng: 2.0000},
    French: {lat: 46.0000, lng: 2.0000},
    "French,": {lat: 46.0000, lng: 2.0000},
    German: {lat: 51.1657, lng: 10.4515},
    "German,": {lat: 51.1657, lng: 10.4515},
    Germanic: {lat: 51.1657, lng: 10.4515},
    "Germanic,": {lat: 51.1657, lng: 10.4515},
    Goth: {lat: 51.1657, lng: 10.4515},
    "Goth,": {lat: 51.1657, lng: 10.4515},
    Gothic: {lat: 51.1657, lng: 10.4515},
    "Gothic,": {lat: 51.1657, lng: 10.4515},
    Dutch: {lat: 52.1326, lng: 5.2913},
    "Dutch,": {lat: 52.1326, lng: 5.2913},
    Greek: {lat: 37.9838, lng: 23.7275},
    "Greek,": {lat: 37.9838, lng: 23.7275},
    Latin: {lat: 41.8719, lng: 12.5674},
    "Latin,": {lat: 41.8719, lng: 12.5674},
    Italian: {lat: 41.8719, lng: 12.5674},
    "Italian,": {lat: 41.8719, lng: 12.5674},
    Spanish: {lat: 40.4637, lng: 3.7492},
    "Spanish,": {lat: 40.4637, lng: 3.7492},
    Castilian: {lat: 40.4637, lng: 3.7492},
    "Castilian,": {lat: 40.4637, lng: 3.7492},
    Egyptian: {lat: 26.8206, lng: 30.8025},
    "Egyptian,": {lat: 26.8206, lng: 30.8025},
    Nordic: {lat: 60.4720, lng: 8.4689},
    "Nordic,": {lat: 60.4720, lng: 8.4689},
    Norwegian: {lat: 60.4720, lng: 8.4689},
    "Norwegian,": {lat: 60.4720, lng: 8.4689},
    Norse: {lat: 60.4720, lng: 8.4689},
    "Norse,": {lat: 60.4720, lng: 8.4689},
    Arabic: {lat: 23.8859, lng: 45.0792},
    "Arabic,": {lat: 23.8859, lng: 45.0792},
    Gaelic: {lat: 53.4129, lng: 8.2439},
    'Gaelic,': {lat: 53.4129, lng: 8.2439},
    Russian: {lat: 61.5240, lng: 105.3188},
    "Russian,": {lat: 61.5240, lng: 105.3188},
    Chinese: {lat: 35.8617, lng: 104.1954},
    "Chinese,": {lat: 35.8617, lng: 104.1954},
    Sanskrit: {lat: 35.8617, lng: 104.1954}, 
    "Sanskrit,": {lat: 35.8617, lng: 104.1954}, 
    Hindi: {lat: 20.5937, lng: 78.9629},
    "Hindi,": {lat: 20.5937, lng: 78.9629},
    "Old Church Slavonic": {lat: 48.6690, lng: 19.6990},
    "Old Church Slavonic,": {lat: 48.6690, lng: 19.6990},
    Slavonic: {lat: 48.6690, lng: 19.6990},
    Hebrew: {lat: 31.7683, lng: 35.2137},
    "Hebrew,": {lat: 31.7683, lng: 35.2137},
    Yiddish: {lat: 51.1657, lng: 10.4515},
    "Yiddish,": {lat: 51.1657, lng: 10.4515},
    Lithuanian: {lat: 55.1694, lng: 23.8813},
    "Lithuanian,": {lat: 55.1694, lng: 23.8813},
    Turkish: {lat: 38.9637, lng: 35.2433},
    "Turkish,": {lat: 38.9637, lng: 35.2433},
    Algonquian: {lat: 45.5017, lng: -73.5673},
    'Algonquian,': {lat: 45.5017, lng: -73.5673},
    Nahuatl: {lat: 20.683056, lng: -88.568611},
    "Nahuatl,": {lat: 20.683056, lng: -88.568611},
    Louisiana: {lat: 29.9511, lng: -90.0715},
    Haitian: {lat: 18.9712, lng: -72.2852},
    Bantu: {lat: 7.3775, lng: 3.9470},
    Kimbundu: {lat: -11.2027, lng: 17.8739}
  }]
}

const reducer = (state = initialState, action ) => {
  switch (action.type) {
    case "ADD_WORD":
      return {...state, word: action.payload}
    case "REMOVE_WORD":
      return {...state, word: ""}
    case "ADD_COORDINATES": 
      return {...state, currentLocation: action.payload}
    case "ADD_ETYMOLOGY": 
      return {...state, etymology: action.payload}
    case "ADD_DATE": 
      return {...state, date: action.payload}
    case "ADD_DEFINITION": 
      return {...state, shortdef: action.payload}
    case "ADD_LANGUAGES":
      return {...state, languages: action.payload}
    case 'CREATE_USER':
      return {...state, currentUser: action.payload}
    case 'LOGIN_USER':
      return {...state, currentUser: action.payload}
    case 'LOGOUT_USER':
      return {...state, currentUser: {}}
    case 'ADD_MOST_COMMON_WORD':
      return {...state, mostCommonWord: action.payload}
    case 'SAVE_MAP':
      return {...state, userMap: action.payload}
    default: 
      return state
  }
}

export default reducer